spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wallet?createDatabaseIfNotExist=true
    username: root
    password: password

api:
  key:
    coin-market-cap: ${API_KEY_COINMARKETCAP}