spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wallet?createDatabaseIfNotExist=true
    username: root
    password: password
  flyway:
    locations: classpath:db/migration,classpath:testdata

api:
  key:
    coin-market-cap: ${API_KEY_COINMARKETCAP}